export * from '~/pages/home/ui/AboutSection'
export * from '~/pages/home/ui/BioSection'
export * from '~/pages/home/ui/GreetingSection'
export * from '~/pages/home/ui/HomePage'
export * from '~/pages/home/ui/ILikeSection'
export * from '~/pages/home/ui/OnTheWebSection'
